name: Deploy

on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
      - name: Install Railway CLI
        run: pnpm add --global @railway/cli
      - name: Deploy to Railway
        run: railway up --service="nestjs-starter"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
